---
title: "Critical Callback Monitor"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
```

Page 1
=======================

Row
-----------------------------------------------------------------------

### Value Box 1

```{r}

```

### Value Box 2

```{r}

```

### Value Box 3

```{r}

```

Row
-----------------------------------------------------------------------

### Chart 1

```{r}

```

### Chart 2

```{r}

```

Page 2
========================

Row
-----------------------------------------------------------------------

### Value Box 1

```{r}

```

### Value Box 2

```{r}

```

### Value Box 3

```{r}

```

Row
-----------------------------------------------------------------------

### Table 1

```{r}

```

### Chart 1

```{r}

```

Page 3
========================

Row
-----------------------------------------------------------------------

### Value Box 1

```{r}

```

### Value Box 2

```{r}

```

### Value Box 3

```{r}

```

Row
-----------------------------------------------------------------------

### Table 1

```{r}

```

### Chart 1

```{r}

```